### PR TITLE
R4 Final Review

### PR DESCRIPTION
**Pull request by amsmith-pro**
https://www.arrowair.com/docs/contributing/guides/release-checklist

### CODE REVIEW

**Comment by owlot** [comment]
## Documents
- [x] ICD
  - [x] Current interfaces (grpc & rest)
  - [x] Current relevant document links
- [x] SDD
  - [x] Description of grpc & rest handler implementations
  - [x] Current sequence diagrams where applicable
  - [x] Current relevant document links
- [x] CONOPS
  - [x] Current information
  - [x] Bibliography (if any citations)
- [x] README (see svc-cargo for example)
  - [x] Badges
  - [x] Accurate installation instructions
  - [x] Current links to other documents
- [x] Any instance of :construction: should genuinely be under construction

## Code (not applicable to examples/ folder)
- [x] No unhandled unwrap()s
- [x] Accurate (!) code comments on all functions
- [x] No `# Arguments` and `# Returns` in function comments
- [x] Function arguments checked where possible
- [x] Sufficient logger (info, warn, and debug) messages
- [x] Sensible Types (unsigned vs. signed)
- [x] No `#[allow(dead_code)]` without good reason
- [x] End all error, info, and debug messages with punctuation (periods, etc.)
- [x] No FIXMEs or TODOs without a projected release (`TODO R4: etc.`)

## REST API
- [x] Return codes accurately documented with openapi
- [x] Return codes make sense
- [x] Sufficiently descriptive error messages
- [x] Do NOT reflect a user's bad input back at them in replies.
    - i.e. "Warning: '{}' is not a valid entry." should instead be "Warning: invalid entry."
    - Use debug messages to see the invalid argument.

## Cargo.toml(s)
- [x] Package versions correct
- [x] No minor versions specified
- [x] Links to crates.io package, not git branch
- [x] Must have `license-file = "LICENSE"` under `[package]`

**Comment by owlot** [comment]
The API Doc generation fails for this one

**Comment by amsmith-pro** [comment]
> The API Doc generation fails for this one

hmm succeeds locally, doesn't like the imported GeoPointZ from the storage dep

**Comment by owlot** [comment]
> > The API Doc generation fails for this one
> 
> hmm succeeds locally, doesn't like the imported GeoPointZ from the storage dep

I'm able to reproduce the error with `make rust-validate-openapi` (maybe needs a `make rust-clean` first for you). It might indeed be the product of changes in `svc-storage`. I'm looking into it now.

**Comment by owlot** [comment]
Requires https://github.com/aetheric-oss/svc-storage/pull/109 to be approved for a release fix.

**Review by owlot — APPROVED** [review]

**Pull request merged**
